# Web Scraping Channel Statistics

In [1]:
import pandas as pd
import altair as alt
from googleapiclient.discovery import build
from pprint import pprint
import matplotlib.pyplot as plt

df = pd.read_excel('data\\channel_ids.xlsx')
ids = df["Channel ID"]

youtube = build('youtube', 'v3', developerKey = "AIzaSyCVTmWL_vvc7EpDsrAR4QPbjACTcezGqPo")

subcount = []
videocount = []
viewcount = []

for channelid in ids:
    request = youtube.channels().list(part='snippet,contentDetails,statistics', id=channelid)
    response = request.execute()
#     print(channelid)
    if(response['items']):
        subcount.append(int(response['items'][0]['statistics']['subscriberCount']))
        videocount.append(int(response['items'][0]['statistics']['videoCount']))
        viewcount.append(int(response['items'][0]['statistics']['viewCount']))                  
#         pprint(response['items'][0]['statistics'])
#         print()
    else:
        continue
        
stats = pd.DataFrame({'Channel Name': df['Channel Name'], 'Subscriber Count': subcount,  'View Count': viewcount, 'Video Count': videocount})
stats.sort_values(by = ['Subscriber Count'], ascending=False, inplace=True)
stats

                   Channel Name  Subscriber Count  View Count  Video Count
0                   3Blue1Brown           5290000   346664087          131
13                    Joma Tech           2210000   181269328          111
9              The Coding Train           1600000   116504398         1220
14                Tech With Tim           1260000   117391953          900
11                      Sentdex           1250000   110562282         1244
10                Corey ShaferÂ            1150000    86988625          232
1   StatQuest with Josh Starmer            956000    50872478          260
2                    Krish Naik            774000    77793430         1687
5                    Tina Huang            554000    24183749          127
6              Alex The Analyst            516000    20698262          221
7                 Luke Barousse            358000    16450448          136
8                 Guy in a Cube            356000    28589533          942
17            Python Programmer            355000    12195017          200
15                Brandon Foltz            280000    25417180          316
4                       Ken Jee            246000     8227885          277
18                  Keith Galli            198000    13506074           78
16               Data Professor            157000     4747226          317
12              Abhishek Thakur             82600     2384511          161
3   The High ROI Data Scientist              3930       60569          119

In [2]:
chart = alt.Chart(stats, title='Subscriber Counts by Channel Name').mark_bar().encode(
    x=alt.X('Channel Name', sort='y', title=None),
    y=alt.Y('Subscriber Count'),
    color=alt.condition(alt.datum['Channel Name'] == 'Joma Tech', alt.value('blue'), alt.value('black')),
    tooltip=['Subscriber Count', 'Channel Name']
)
chart.configure_axisX(ticks=False)
chart

alt.Chart(...)

In [3]:
chart = alt.Chart(stats, title='View Counts by Channel Name').mark_bar().encode(
    x=alt.X('Channel Name', sort='y', title=None),
    y=alt.Y('View Count'),
    color=alt.condition(alt.datum['Channel Name'] == 'Joma Tech', alt.value('blue'), alt.value('black')),
    tooltip=['View Count', 'Channel Name']
)
chart.configure_axisX(ticks=False)
chart

alt.Chart(...)

In [4]:
chart = alt.Chart(stats, title='Video Counts by Channel Name').mark_bar().encode(
    x=alt.X('Channel Name', sort='y', title=None),
    y=alt.Y('Video Count'),
    color=alt.condition(alt.datum['Channel Name'] == 'Joma Tech', alt.value('blue'), alt.value('black')),
    tooltip=['Video Count', 'Channel Name']
)
chart.configure_axisX(ticks=False)
chart

alt.Chart(...)

# Survey Data Analysis

In [5]:
# define a function : map the values "Easy" : 1, "Medium" : 2 and "Hard" : 3
def map_values(value):
    if value == 'Easy':
        return 1
    elif value == 'Medium':
        return 2
    elif value == 'Hard':
        return 3
    else:
        return value


responses = pd.read_excel('data\\responses.xlsx')
responses.head()

,DATA 530,DATA 580,DATA 541,DATA 531,DATA 532,DATA 540,DATA 553,DATA 570,DATA 533,DATA 542,DATA 543,DATA 571,DATA 534,DATA 550,DATA 572,DATA 581,DATA 551,DATA 552,DATA 573,DATA 583
0,Easy,Hard,Easy,Medium,Easy,Easy,Medium,Easy,Easy,Easy,Medium,Medium,Medium,Medium,Easy,Hard,Medium,Easy,Hard,Hard
1,Medium,Medium,Medium,Medium,Medium,Easy,Medium,Medium,Hard,Medium,Medium,Hard,Hard,Medium,Hard,Hard,Hard,Medium,Hard,Hard
2,Easy,Medium,Medium,Medium,Hard,Easy,Easy,Medium,Easy,Medium,Easy,Medium,Hard,Easy,Medium,Hard,Medium,Medium,Hard,Hard
3,Easy,Medium,Medium,Easy,Medium,Easy,Hard,Medium,Easy,Medium,Medium,Medium,Medium,Hard,Medium,Hard,Medium,Medium,Medium,Hard
4,Easy,Medium,Easy,Hard,Medium,Easy,Easy,Medium,Easy,Medium,Hard,Easy,Medium,Medium,Easy,Medium,Easy,Easy,Medium,Medium

In [6]:
data = responses.applymap(map_values)
data.head()

,DATA 530,DATA 580,DATA 541,DATA 531,DATA 532,DATA 540,DATA 553,DATA 570,DATA 533,DATA 542,DATA 543,DATA 571,DATA 534,DATA 550,DATA 572,DATA 581,DATA 551,DATA 552,DATA 573,DATA 583
0,1,3,1,2,1,1,2,1,1,1,2,2,2,2,1,3,2,1,3,3
1,2,2,2,2,2,1,2,2,3,2,2,3,3,2,3,3,3,2,3,3
2,1,2,2,2,3,1,1,2,1,2,1,2,3,1,2,3,2,2,3,3
3,1,2,2,1,2,1,3,2,1,2,2,2,2,3,2,3,2,2,2,3
4,1,2,1,3,2,1,1,2,1,2,3,1,2,2,1,2,1,1,2,2

In [7]:
one = list(((data.eq(1).sum()).to_dict()).values())
two = list(((data.eq(2).sum()).to_dict()).values())
three = list(((data.eq(3).sum()).to_dict()).values())
courses = list(data.columns)

mydata = pd.DataFrame({'courses': courses, 'ones' : one, 'twos': two, 'threes': three})
mydata.head()

    courses  ones  twos  threes
0  DATA 530    17     3       1
1  DATA 580     3    10       8
2  DATA 541    10    11       0
3  DATA 531    11     7       3
4  DATA 532     6    11       4

In [8]:
onechart = alt.Chart(mydata, title=alt.TitleParams(text = ["Level of difficulty: Easy"])).mark_bar().encode(
                     x=alt.X('courses', sort ='y', title = None, axis = alt.Axis(ticks=False)),
                     y=alt.Y('ones', title = "Count of responses"),
                     color=alt.condition(alt.datum.ones == mydata['ones'].max(),alt.value('green'), alt.value('black')))
onechart

alt.Chart(...)

In [9]:
twochart = alt.Chart(mydata, title=alt.TitleParams(text = ["Level of difficulty: Medium"])).mark_bar().encode(
                     x=alt.X('courses', sort ='y', title = None, axis = alt.Axis(ticks=False)),
                     y=alt.Y('twos', title = "Count of responses"),
                     color=alt.condition(alt.datum.twos == mydata['twos'].max(),alt.value('#FAD02C'), alt.value('black')))
twochart

alt.Chart(...)

In [10]:
threechart = alt.Chart(mydata, title=alt.TitleParams(text = ["Level of difficulty: Hard"])).mark_bar().encode(
                       x=alt.X('courses', sort ='y', title = None, axis = alt.Axis(ticks=False)),
                       y=alt.Y('threes', title = "Count of responses"),
                       color=alt.condition(alt.datum.threes==mydata['threes'].max(),alt.value('red'),alt.value('black')))
threechart

alt.Chart(...)

In [11]:
mydata.sort_values(by = ['threes'], ascending = False)

     courses  ones  twos  threes
19  DATA 583     1     3      17
15  DATA 581     2     3      16
1   DATA 580     3    10       8
6   DATA 553     9     5       7
12  DATA 534     3    11       7
18  DATA 573     2    13       6
13  DATA 550     5    11       5
11  DATA 571     5    11       5
16  DATA 551     2    15       4
14  DATA 572     5    12       4
10  DATA 543     8     9       4
7   DATA 570     5    12       4
4   DATA 532     6    11       4
8   DATA 533     7    11       3
3   DATA 531    11     7       3
9   DATA 542     9    10       2
17  DATA 552    10     9       2
0   DATA 530    17     3       1
5   DATA 540    15     6       0
2   DATA 541    10    11       0

In [12]:
mydata.sort_values(by = ['twos'], ascending = False)

     courses  ones  twos  threes
16  DATA 551     2    15       4
18  DATA 573     2    13       6
7   DATA 570     5    12       4
14  DATA 572     5    12       4
13  DATA 550     5    11       5
12  DATA 534     3    11       7
11  DATA 571     5    11       5
8   DATA 533     7    11       3
4   DATA 532     6    11       4
2   DATA 541    10    11       0
9   DATA 542     9    10       2
1   DATA 580     3    10       8
17  DATA 552    10     9       2
10  DATA 543     8     9       4
3   DATA 531    11     7       3
5   DATA 540    15     6       0
6   DATA 553     9     5       7
0   DATA 530    17     3       1
15  DATA 581     2     3      16
19  DATA 583     1     3      17